import type { CourseCatalogItem } from "./types"

export const courseCategories = [
  { id: "health", name: "Healthcare & Wellness", color: "from-pink-500 to-rose-500" },
  { id: "business", name: "Business & Management", color: "from-blue-500 to-cyan-500" },
  { id: "technology", name: "IT & Technology", color: "from-purple-500 to-indigo-500" },
  { id: "creative", name: "Creative Arts & Design", color: "from-orange-500 to-red-500" },
  { id: "education", name: "Education & Training", color: "from-green-500 to-emerald-500" },
  { id: "agriculture", name: "Agriculture & Environment", color: "from-teal-500 to-green-500" },
  { id: "finance", name: "Finance & Accounting", color: "from-yellow-500 to-amber-500" },
  { id: "legal", name: "Legal & Compliance", color: "from-gray-600 to-gray-800" },
  { id: "hospitality", name: "Hospitality & Tourism", color: "from-indigo-500 to-purple-500" },
  { id: "trades", name: "Trades & Technical Skills", color: "from-red-500 to-pink-500" },
]

export const courseCatalog: CourseCatalogItem[] = [
  // A Courses
  {
    id: "accounting",
    letter: "A",
    certificateTitle: "Accounting Fundamentals",
    diplomaTitle: "Accounting Professional",
    category: "finance",
    icon: "Calculator",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "artificial-intelligence",
    letter: "A",
    certificateTitle: "Artificial Intelligence Basics",
    diplomaTitle: "AI Engineering",
    category: "technology",
    icon: "Brain",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "agriculture",
    letter: "A",
    certificateTitle: "Agriculture Management",
    diplomaTitle: "Agribusiness Leadership",
    category: "agriculture",
    icon: "Sprout",
    color: "from-teal-500 to-green-500",
  },
  {
    id: "art-therapy",
    letter: "A",
    certificateTitle: "Art Therapy",
    diplomaTitle: "Clinical Art Therapy",
    category: "health",
    icon: "Palette",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "android-development",
    letter: "A",
    certificateTitle: "Android Development",
    diplomaTitle: "Advanced Android Engineering",
    category: "technology",
    icon: "Smartphone",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "arabic-language",
    letter: "A",
    certificateTitle: "Arabic Language",
    diplomaTitle: "Arabic Translation",
    category: "education",
    icon: "Languages",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "aviation-safety",
    letter: "A",
    certificateTitle: "Aviation Safety",
    diplomaTitle: "Aviation Management",
    category: "business",
    icon: "Plane",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "anthropology",
    letter: "A",
    certificateTitle: "Anthropology",
    diplomaTitle: "Cultural Anthropology",
    category: "education",
    icon: "Users",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "apparel-design",
    letter: "A",
    certificateTitle: "Apparel Design",
    diplomaTitle: "Fashion Technology",
    category: "creative",
    icon: "Shirt",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "aquaculture",
    letter: "A",
    certificateTitle: "Aquaculture",
    diplomaTitle: "Aquaculture Management",
    category: "agriculture",
    icon: "Fish",
    color: "from-teal-500 to-green-500",
  },

  // B Courses
  {
    id: "business-management",
    letter: "B",
    certificateTitle: "Business Management",
    diplomaTitle: "Business Administration",
    category: "business",
    icon: "Briefcase",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "blockchain",
    letter: "B",
    certificateTitle: "Blockchain Technology",
    diplomaTitle: "Blockchain Development",
    category: "technology",
    icon: "Link",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "biotechnology",
    letter: "B",
    certificateTitle: "Biotechnology",
    diplomaTitle: "Biotech Research",
    category: "health",
    icon: "Microscope",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "baking-arts",
    letter: "B",
    certificateTitle: "Baking Arts",
    diplomaTitle: "Professional Patisserie",
    category: "hospitality",
    icon: "Cookie",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "bookkeeping",
    letter: "B",
    certificateTitle: "Bookkeeping",
    diplomaTitle: "Financial Accounting",
    category: "finance",
    icon: "BookOpen",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "behavioral-psychology",
    letter: "B",
    certificateTitle: "Behavioral Psychology",
    diplomaTitle: "Clinical Psychology",
    category: "health",
    icon: "Brain",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "brand-management",
    letter: "B",
    certificateTitle: "Brand Management",
    diplomaTitle: "Strategic Branding",
    category: "business",
    icon: "Target",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "building-construction",
    letter: "B",
    certificateTitle: "Building Construction",
    diplomaTitle: "Construction Management",
    category: "trades",
    icon: "Building",
    color: "from-red-500 to-pink-500",
  },
  {
    id: "business-analytics",
    letter: "B",
    certificateTitle: "Business Analytics",
    diplomaTitle: "Data Science",
    category: "technology",
    icon: "BarChart",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "biodiversity",
    letter: "B",
    certificateTitle: "Biodiversity Conservation",
    diplomaTitle: "Wildlife Management",
    category: "agriculture",
    icon: "Leaf",
    color: "from-teal-500 to-green-500",
  },

  // C Courses
  {
    id: "cybersecurity",
    letter: "C",
    certificateTitle: "Cybersecurity",
    diplomaTitle: "Ethical Hacking",
    category: "technology",
    icon: "Shield",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "culinary-arts",
    letter: "C",
    certificateTitle: "Culinary Arts",
    diplomaTitle: "Chef Training",
    category: "hospitality",
    icon: "ChefHat",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "counseling",
    letter: "C",
    certificateTitle: "Counseling Skills",
    diplomaTitle: "Professional Counseling",
    category: "health",
    icon: "Heart",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "cloud-computing",
    letter: "C",
    certificateTitle: "Cloud Computing",
    diplomaTitle: "AWS Solutions Architect",
    category: "technology",
    icon: "Cloud",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "content-writing",
    letter: "C",
    certificateTitle: "Content Writing",
    diplomaTitle: "Digital Content Strategy",
    category: "creative",
    icon: "PenTool",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "child-development",
    letter: "C",
    certificateTitle: "Child Development",
    diplomaTitle: "Early Childhood Education",
    category: "education",
    icon: "Baby",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "carpentry",
    letter: "C",
    certificateTitle: "Carpentry",
    diplomaTitle: "Furniture Design",
    category: "trades",
    icon: "Hammer",
    color: "from-red-500 to-pink-500",
  },
  {
    id: "corporate-law",
    letter: "C",
    certificateTitle: "Corporate Law",
    diplomaTitle: "Legal Practice",
    category: "legal",
    icon: "Scale",
    color: "from-gray-600 to-gray-800",
  },
  {
    id: "computer-networking",
    letter: "C",
    certificateTitle: "Computer Networking",
    diplomaTitle: "Network Engineering",
    category: "technology",
    icon: "Network",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "climate-change",
    letter: "C",
    certificateTitle: "Climate Change Studies",
    diplomaTitle: "Environmental Policy",
    category: "agriculture",
    icon: "Globe",
    color: "from-teal-500 to-green-500",
  },

  // Continue with D-Z... (adding representative courses for each letter)
  // D Courses
  {
    id: "digital-marketing",
    letter: "D",
    certificateTitle: "Digital Marketing",
    diplomaTitle: "Digital Strategy",
    category: "business",
    icon: "Megaphone",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "data-analysis",
    letter: "D",
    certificateTitle: "Data Analysis",
    diplomaTitle: "Business Intelligence",
    category: "technology",
    icon: "Database",
    color: "from-purple-500 to-indigo-500",
  },

  // E Courses
  {
    id: "entrepreneurship",
    letter: "E",
    certificateTitle: "Entrepreneurship",
    diplomaTitle: "Startup Management",
    category: "business",
    icon: "Rocket",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "event-planning",
    letter: "E",
    certificateTitle: "Event Planning",
    diplomaTitle: "Event Management",
    category: "hospitality",
    icon: "Calendar",
    color: "from-indigo-500 to-purple-500",
  },

  // F Courses
  {
    id: "financial-planning",
    letter: "F",
    certificateTitle: "Financial Planning",
    diplomaTitle: "Wealth Management",
    category: "finance",
    icon: "TrendingUp",
    color: "from-yellow-500 to-amber-500",
  },
  {
    id: "fashion-design",
    letter: "F",
    certificateTitle: "Fashion Design",
    diplomaTitle: "Fashion Merchandising",
    category: "creative",
    icon: "Sparkles",
    color: "from-orange-500 to-red-500",
  },

  // G Courses
  {
    id: "graphic-design",
    letter: "G",
    certificateTitle: "Graphic Design",
    diplomaTitle: "Visual Communication",
    category: "creative",
    icon: "Palette",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "game-development",
    letter: "G",
    certificateTitle: "Game Development",
    diplomaTitle: "Game Design",
    category: "technology",
    icon: "Gamepad2",
    color: "from-purple-500 to-indigo-500",
  },

  // H Courses
  {
    id: "human-resources",
    letter: "H",
    certificateTitle: "Human Resources",
    diplomaTitle: "HR Management",
    category: "business",
    icon: "Users",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "hospitality",
    letter: "H",
    certificateTitle: "Hospitality",
    diplomaTitle: "Hotel Management",
    category: "hospitality",
    icon: "Hotel",
    color: "from-indigo-500 to-purple-500",
  },

  // I Courses
  {
    id: "interior-design",
    letter: "I",
    certificateTitle: "Interior Design",
    diplomaTitle: "Space Planning",
    category: "creative",
    icon: "Home",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "it-support",
    letter: "I",
    certificateTitle: "IT Support",
    diplomaTitle: "IT Management",
    category: "technology",
    icon: "Laptop",
    color: "from-purple-500 to-indigo-500",
  },

  // J Courses
  {
    id: "journalism",
    letter: "J",
    certificateTitle: "Journalism",
    diplomaTitle: "Investigative Journalism",
    category: "creative",
    icon: "Newspaper",
    color: "from-orange-500 to-red-500",
  },

  // K Courses
  {
    id: "kindergarten-teaching",
    letter: "K",
    certificateTitle: "Kindergarten Teaching",
    diplomaTitle: "Early Years Education",
    category: "education",
    icon: "School",
    color: "from-green-500 to-emerald-500",
  },

  // L Courses
  {
    id: "leadership",
    letter: "L",
    certificateTitle: "Leadership",
    diplomaTitle: "Executive Leadership",
    category: "business",
    icon: "Award",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "logistics",
    letter: "L",
    certificateTitle: "Logistics",
    diplomaTitle: "Supply Chain Management",
    category: "business",
    icon: "Truck",
    color: "from-blue-500 to-cyan-500",
  },

  // M Courses
  {
    id: "marketing",
    letter: "M",
    certificateTitle: "Marketing",
    diplomaTitle: "Strategic Marketing",
    category: "business",
    icon: "TrendingUp",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "mental-health",
    letter: "M",
    certificateTitle: "Mental Health Counseling",
    diplomaTitle: "Clinical Psychology",
    category: "health",
    icon: "Heart",
    color: "from-pink-500 to-rose-500",
  },

  // N Courses
  {
    id: "nursing",
    letter: "N",
    certificateTitle: "Nursing",
    diplomaTitle: "Registered Nursing",
    category: "health",
    icon: "Stethoscope",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "nutrition",
    letter: "N",
    certificateTitle: "Nutrition",
    diplomaTitle: "Clinical Dietetics",
    category: "health",
    icon: "Apple",
    color: "from-pink-500 to-rose-500",
  },

  // O Courses
  {
    id: "office-administration",
    letter: "O",
    certificateTitle: "Office Administration",
    diplomaTitle: "Executive Assistance",
    category: "business",
    icon: "FileText",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "organic-farming",
    letter: "O",
    certificateTitle: "Organic Farming",
    diplomaTitle: "Sustainable Agriculture",
    category: "agriculture",
    icon: "Sprout",
    color: "from-teal-500 to-green-500",
  },

  // P Courses
  {
    id: "project-management",
    letter: "P",
    certificateTitle: "Project Management",
    diplomaTitle: "PMP Preparation",
    category: "business",
    icon: "ClipboardCheck",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "photography",
    letter: "P",
    certificateTitle: "Photography",
    diplomaTitle: "Professional Photography",
    category: "creative",
    icon: "Camera",
    color: "from-orange-500 to-red-500",
  },

  // Q Courses
  {
    id: "quality-assurance",
    letter: "Q",
    certificateTitle: "Quality Assurance",
    diplomaTitle: "Quality Management",
    category: "business",
    icon: "CheckCircle",
    color: "from-blue-500 to-cyan-500",
  },

  // R Courses
  {
    id: "real-estate",
    letter: "R",
    certificateTitle: "Real Estate",
    diplomaTitle: "Property Management",
    category: "business",
    icon: "Building2",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "renewable-energy",
    letter: "R",
    certificateTitle: "Renewable Energy",
    diplomaTitle: "Sustainable Energy Systems",
    category: "agriculture",
    icon: "Sun",
    color: "from-teal-500 to-green-500",
  },

  // S Courses
  {
    id: "social-media-marketing",
    letter: "S",
    certificateTitle: "Social Media Marketing",
    diplomaTitle: "Digital Strategy",
    category: "business",
    icon: "Share2",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "software-engineering",
    letter: "S",
    certificateTitle: "Software Engineering",
    diplomaTitle: "Full Stack Development",
    category: "technology",
    icon: "Code",
    color: "from-purple-500 to-indigo-500",
  },

  // T Courses
  {
    id: "teaching",
    letter: "T",
    certificateTitle: "Teaching",
    diplomaTitle: "Education Leadership",
    category: "education",
    icon: "GraduationCap",
    color: "from-green-500 to-emerald-500",
  },
  {
    id: "tourism",
    letter: "T",
    certificateTitle: "Tourism",
    diplomaTitle: "Travel & Tourism Management",
    category: "hospitality",
    icon: "Palmtree",
    color: "from-indigo-500 to-purple-500",
  },

  // U Courses
  {
    id: "ui-ux-design",
    letter: "U",
    certificateTitle: "UI/UX Design",
    diplomaTitle: "User Experience Strategy",
    category: "creative",
    icon: "Monitor",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "urban-farming",
    letter: "U",
    certificateTitle: "Urban Farming",
    diplomaTitle: "Agricultural Innovation",
    category: "agriculture",
    icon: "Building",
    color: "from-teal-500 to-green-500",
  },

  // V Courses
  {
    id: "video-production",
    letter: "V",
    certificateTitle: "Video Production",
    diplomaTitle: "Film & Media Production",
    category: "creative",
    icon: "Video",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "virtual-assistance",
    letter: "V",
    certificateTitle: "Virtual Assistance",
    diplomaTitle: "Executive Support",
    category: "business",
    icon: "Headphones",
    color: "from-blue-500 to-cyan-500",
  },

  // W Courses
  {
    id: "web-development",
    letter: "W",
    certificateTitle: "Web Development",
    diplomaTitle: "Full Stack Development",
    category: "technology",
    icon: "Globe",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "welding",
    letter: "W",
    certificateTitle: "Welding",
    diplomaTitle: "Metal Fabrication",
    category: "trades",
    icon: "Flame",
    color: "from-red-500 to-pink-500",
  },

  // X Courses
  {
    id: "xray-technology",
    letter: "X",
    certificateTitle: "X-Ray Technology",
    diplomaTitle: "Radiography",
    category: "health",
    icon: "Scan",
    color: "from-pink-500 to-rose-500",
  },

  // Y Courses
  {
    id: "yoga-instruction",
    letter: "Y",
    certificateTitle: "Yoga Instruction",
    diplomaTitle: "Yoga Therapy",
    category: "health",
    icon: "Heart",
    color: "from-pink-500 to-rose-500",
  },
  {
    id: "youth-counseling",
    letter: "Y",
    certificateTitle: "Youth Counseling",
    diplomaTitle: "Adolescent Psychology",
    category: "health",
    icon: "Users",
    color: "from-pink-500 to-rose-500",
  },

  // Z Courses
  {
    id: "zoology",
    letter: "Z",
    certificateTitle: "Zoology",
    diplomaTitle: "Wildlife Conservation",
    category: "agriculture",
    icon: "Rat",
    color: "from-teal-500 to-green-500",
  },
]

export function getCoursesByLetter(letter: string) {
  return courseCatalog.filter((course) => course.letter === letter)
}

export function getAllLetters() {
  return Array.from(new Set(courseCatalog.map((c) => c.letter))).sort()
}
